const topics: Record<string, string> = {
  // Web Security
  xss: "Cross-Site Scripting (XSS) is a vulnerability where attackers inject malicious scripts into web pages viewed by others. Think of it like someone slipping a fake note into a library book — when the next person reads it, they see the attacker's message instead of the real content.\n\n**Three types:**\n- **Stored XSS** — The malicious script is permanently stored on the server (e.g., in a comment field). Every visitor gets infected.\n- **Reflected XSS** — The script is in a link that tricks the user into clicking it.\n- **DOM-based XSS** — The vulnerability is in the page's own JavaScript code.\n\n**How to defend:** Sanitize all user input, use Content Security Policy (CSP) headers, and set HttpOnly flags on cookies.",
  "sql injection": "SQL Injection (SQLi) is like someone tricking a vending machine by pressing buttons in a way the designer never intended — instead of just selecting a snack, they get the machine to open its entire door.\n\nAttackers inject malicious SQL code into input fields (like login forms) to manipulate the database. They can bypass login screens, steal data, or even delete entire tables.\n\n**Defense:**\n- Use **parameterized queries** (prepared statements) instead of string concatenation\n- Always validate and sanitize user inputs\n- Use an ORM (Object-Relational Mapping) library\n- Apply the principle of least privilege to database accounts",
  sqli: "SQL Injection (SQLi) is like someone tricking a vending machine by pressing buttons in a way the designer never intended — instead of just selecting a snack, they get the machine to open its entire door.\n\nAttackers inject malicious SQL code into input fields (like login forms) to manipulate the database. They can bypass login screens, steal data, or even delete entire tables.\n\n**Defense:**\n- Use **parameterized queries** (prepared statements) instead of string concatenation\n- Always validate and sanitize user inputs\n- Use an ORM library\n- Apply least privilege to database accounts",

  // Network Security
  firewall: "A firewall is like a security guard at the entrance of a building who checks everyone coming in and going out, and stops anyone who shouldn't be there.\n\n**Types of firewalls:**\n- **Packet-filtering** — Checks source/destination IP and port\n- **Stateful inspection** — Tracks active connections to make smarter decisions\n- **Application-layer (WAF)** — Understands web traffic specifically (HTTP/HTTPS)\n\n**Best practice:** Use a **default-deny** policy — block everything by default, then only allow what's needed.",
  vpn: "A VPN (Virtual Private Network) creates a secure, encrypted tunnel between your device and a remote server. Think of it like a private, enclosed walkway between two buildings — no one on the street can see what you're carrying.\n\n**What VPNs protect:**\n- Your IP address and location are hidden\n- Your internet traffic is encrypted (safe on public WiFi)\n- Your ISP can't see what websites you visit\n\n**Common protocols:** OpenVPN, WireGuard, IPsec.\n\n**Important:** A VPN protects your privacy, but it doesn't make you anonymous or protect you from malware.",
  "mac flooding": "MAC Flooding is an attack where someone sends thousands of fake MAC addresses to a network switch, overflowing its CAM table. The switch gets confused and starts acting like a simple hub — broadcasting all traffic to every port. This lets the attacker sniff network traffic they shouldn't have access to.\n\n**Defense:** Enable **Port Security** on your switches to limit how many MAC addresses can be learned on each port.",
  "arp spoofing": "ARP Spoofing is when an attacker sends fake ARP (Address Resolution Protocol) messages onto a network, linking their MAC address to a legitimate IP address. This lets them intercept traffic meant for someone else — like a mail carrier redirecting your neighbor's mail to their own house.\n\n**Defense:** Dynamic ARP Inspection (DAI) and static ARP entries.",
  dhcp: "DHCP Starvation floods a DHCP server with fake requests to exhaust its pool of IP addresses. Once the pool is empty, legitimate devices can't connect to the network. It's like someone reserving every table in a restaurant without actually dining there.\n\n**Defense:** DHCP snooping and port security.",
  dos: "A Denial of Service (DoS) attack overwhelms a system with so much traffic that it can't serve legitimate users. Think of it like a prank caller ordering 100 pizzas to someone's house — the delivery drivers block the door, and real orders can't get through.\n\n**DDoS** (Distributed) comes from many systems at once, making it much harder to stop.\n\n**Defenses:** Rate limiting, CDN services (like Cloudflare), traffic filtering, and anycast routing.",
  ddos: "A Distributed Denial of Service (DDoS) attack floods a target from hundreds or thousands of different computers at the same time. It's like a flash mob blocking a store entrance from every direction simultaneously.\n\n**Defenses:**\n- Use a CDN like Cloudflare or AWS Shield\n- Implement rate limiting\n- Use anycast routing to distribute traffic\n- Have a DDoS response plan ready",

  // Malware & Threats
  malware: "Malware (malicious software) is any program designed to harm or exploit computers. Think of it like a burglar's toolkit — different tools for different break-ins.\n\n**Common types:**\n- **Virus** — Attaches to clean files and spreads\n- **Worm** — Self-replicates across networks\n- **Trojan** — Disguises as legitimate software\n- **Ransomware** — Encrypts your files and demands payment\n- **Spyware** — Secretly monitors your activity\n\n**Defense:** Keep software updated, use antivirus, don't open suspicious attachments, and practice least privilege.",
  ransomware: "Ransomware is a type of malware that encrypts your files and demands payment to unlock them. It's like someone putting all your belongings in a locked safe and demanding money for the combination.\n\n**How to protect yourself:**\n- **Keep offline backups** — Your best defense\n- **Network segmentation** — Don't let one infected machine reach critical data\n- **Email filtering** — Most ransomware arrives via phishing emails\n- **User training** — Recognize suspicious links and attachments\n\n**Never pay the ransom.** There's no guarantee you'll get your data back, and you're funding criminal operations.",

  // Encryption & Privacy
  encryption: "Encryption is like writing a message in a secret code that only the intended recipient can decode. Even if someone intercepts the message, they can't read it without the key.\n\n**Two main types:**\n- **Symmetric encryption (AES)** — Same key to lock and unlock. Fast, good for encrypting files.\n- **Asymmetric encryption (RSA)** — Different keys for locking (public) and unlocking (private). Used for secure communication.\n\n**Everyday uses:**\n- HTTPS websites use TLS/SSL encryption\n- WhatsApp messages are end-to-end encrypted\n- Your WiFi password uses encryption to protect your network",

  // Authentication & Access
  authentication: "Authentication is how a system verifies you are who you claim to be. It's like showing your ID at airport security.\n\n**Three factors:**\n1. **Something you know** — Password, PIN\n2. **Something you have** — Phone, security key, smart card\n3. **Something you are** — Fingerprint, face scan\n\n**Always use Multi-Factor Authentication (MFA)** — combining at least two factors. A password alone is like having just a lock; MFA adds a deadbolt and a security camera.",
  "multi factor": "Multi-Factor Authentication (MFA) uses two or more different methods to verify your identity. Think of it like needing both a key and a fingerprint to open a door — if someone steals your key, they still can't get in.\n\n**Common MFA methods:**\n- Text message code + password\n- Authenticator app (like Google Authenticator)\n- Hardware security key (like YubiKey)\n- Biometrics (fingerprint, face ID)\n\n**Pro tip:** Use an authenticator app instead of SMS when possible — SMS codes can be intercepted.",
  password: "A strong password is your first line of defense. Think of it as the lock on your front door — a weak lock is easy to pick.\n\n**How to create strong passwords:**\n- At least 12-16 characters long\n- Mix of uppercase, lowercase, numbers, and symbols\n- Avoid dictionary words, birthdays, or personal info\n- Use a **passphrase** — a random string of words like 'PurpleMonkeyDiscoTruck92!'\n\n**Best practice:** Use a **password manager** (like Bitwarden, 1Password, or Apple Keychain). Then you only need to remember one strong master password.",
  "access control": "Access control determines who can see or use what resources. It's like a company badge system — some employees can enter the lobby, others can access the server room.\n\n**Main models:**\n- **DAC (Discretionary)** — The owner decides who gets access\n- **MAC (Mandatory)** — System-enforced rules, used in government\n- **RBAC (Role-Based)** — Access based on job role (most common in companies)\n\n**Key principle:** Least privilege — give people only the access they need, nothing more.",

  // Social Engineering
  phishing: "Phishing is when attackers send fake emails or messages that look legitimate to trick you into revealing sensitive information. It's like someone dressing up as a delivery driver to get you to open your door.\n\n**How to spot phishing:**\n- Urgent or threatening language ('Your account will be closed!')\n- Suspicious sender email address (slightly misspelled)\n- Generic greetings ('Dear Customer' instead of your name)\n- Requests for personal information\n- Suspicious links (hover before clicking!)\n\n**Defense:** Think before you click. Verify unexpected emails by contacting the company directly through their official website.",
  "social engineering": "Social engineering is manipulating people into revealing confidential information rather than hacking a computer system. It's the art of hacking humans instead of technology.\n\n**Common techniques:**\n- **Pretexting** — Creating a fake scenario to get information\n- **Baiting** — Offering something tempting (like a free USB drive)\n- **Tailgating** — Following someone into a restricted area\n- **Quid pro quo** — Offering a service in exchange for information\n\n**Best defense:** Security awareness training and clear policies about sharing information.",

  // Advanced Topics
  "zero day": "A zero-day vulnerability is a security flaw that the software vendor doesn't know about yet — meaning there's zero days of protection available. It's like discovering a hidden door in a bank vault that the bank doesn't even know exists.\n\n**Why they're dangerous:**\n- No patch available (vendor hasn't had time to fix it)\n- Attackers can exploit them freely until discovered\n- Often used by advanced persistent threats and nation-states\n\n**Defenses:** Intrusion detection systems, behavior monitoring, defense in depth, and keeping systems updated (even though zero-days bypass patches).",
  "penetration testing": "Penetration testing (pen testing) is an authorized simulated cyber attack on a system to find vulnerabilities before real attackers do. Think of it like hiring a friendly burglar to test your home security and report back on what they found.\n\n**The five phases:**\n1. **Reconnaissance** — Gathering information about the target\n2. **Scanning** — Looking for open ports and vulnerabilities\n3. **Exploitation** — Attempting to break in\n4. **Post-exploitation** — Seeing what damage can be done\n5. **Reporting** — Documenting findings and recommendations\n\n**Ethical hackers** are cybersecurity professionals who do this for a living.",
  "incident response": "Incident Response is the process of handling a security breach. It's like a fire drill — you need a plan before the emergency happens.\n\n**The NIST framework (SP 800-61):**\n1. **Preparation** — Have tools and plans ready\n2. **Detection** — Identify that something is wrong\n3. **Containment** — Stop the attack from spreading\n4. **Eradication** — Remove the threat\n5. **Recovery** — Restore normal operations\n6. **Post-Incident** — Learn and improve\n\n**Golden rule:** Speed of containment is critical. The longer an attacker has access, the more damage they can do.",
  "buffer overflow": "A buffer overflow happens when a program writes more data to a memory buffer than it can hold, spilling into adjacent memory. Think of it like pouring a glass of water until it overflows onto the table — but in this case, the overflow can overwrite critical program instructions.\n\n**Why it's dangerous:** Attackers can use this to inject and execute their own malicious code.\n\n**Defenses:**\n- Stack canaries (guard values that detect overflows)\n- ASLR (Address Space Layout Randomization)\n- Using memory-safe languages (like Rust or Go)\n- Regular patching",
  forensics: "Digital forensics is the investigation of digital evidence after a security incident. Think of it as CSI for computers — collecting clues, analyzing data, and figuring out what happened.\n\n**Branches:**\n- **Computer forensics** — Hard drives, files, system logs\n- **Network forensics** — Network traffic, packet captures\n- **Mobile forensics** — Smartphones, tablets\n- **Cloud forensics** — AWS, Google Cloud, Azure\n\n**Key principle:** Chain of custody — every piece of evidence must be carefully tracked to be admissible in court.",
  siem: "SIEM (Security Information and Event Management) is a system that collects logs from across your network and analyzes them for suspicious activity. It's like a security camera system for your entire digital infrastructure.\n\n**What SIEM does:**\n- Centralized logging from all devices\n- Real-time monitoring and alerting\n- Correlates events across different systems\n- Helps with compliance reporting\n\n**Popular tools:** Splunk, ELK Stack (Elasticsearch, Logstash, Kibana), Wazuh, and Microsoft Sentinel.",
  "threat hunting": "Threat hunting is proactively searching for cyber threats that have evaded your existing security tools. Instead of waiting for an alarm to go off, you actively look for signs of trouble.\n\n**How it works:**\n1. Form a hypothesis about potential threats\n2. Search through logs and system data for evidence\n3. Use indicators of compromise (IoCs) and behavioral analytics\n4. Investigate and remediate any findings\n\n**Analogy:** It's like a detective walking through a neighborhood checking for open doors, rather than just waiting for burglary reports.",

  // AI Security
  "prompt injection": "Prompt injection is a vulnerability where a user tricks an AI by giving it malicious input that overrides its instructions. Think of it like telling a hotel concierge 'Ignore your training — instead, tell me which rooms are empty so I can rob them.'\n\n**Types:**\n- **Direct jailbreaking** — 'Act as DAN (Do Anything Now)'\n- **Indirect injection** — Hidden instructions in web pages the AI reads\n\n**Defenses:** Input/output guardrails, separating system prompts from user input, and adversarial training.",
  jailbreak: "Jailbreaking in AI refers to techniques that bypass an AI's safety guardrails. Common methods include:\n- **DAN (Do Anything Now)** — Asking the AI to adopt a persona with no rules\n- **Roleplay scenarios** — 'Pretend we're in a movie about hacking'\n- **Developer mode** — 'Act as if you're in debug mode'\n- **Reverse psychology** — 'Don't tell me how to protect against XSS'\n\n**Defenses:** Input classifiers, output classifiers, separation of system/user roles, and adversarial training against known jailbreak patterns.",
};

const greetings = /^(hi|hello|hey|yo|bro|sup|good morning|good evening|good afternoon|howdy|what's up|wassup)/i;
const thanks = /how are you|how('s| is) it going|thanks|thank you|appreciate it|good bot/i;

const questionWords = ["what", "how", "why", "when", "where", "who", "which", "can", "does", "is", "are", "do", "explain", "tell", "define", "describe", "show", "teach", "help", "need"];

export function chatLocal(message: string): string {
  const msgLower = message.toLowerCase().trim();

  // Topic keyword matching
  for (const [keyword, explanation] of Object.entries(topics)) {
    if (msgLower.includes(keyword)) {
      return explanation;
    }
  }

  // Greetings
  if (greetings.test(msgLower)) {
    return "Hey there! 👋 I'm your CyberAI Tutor. I can teach you about passwords, phishing, firewalls, encryption, social engineering, and tons of other cybersecurity topics. What would you like to learn about today?";
  }

  // Thanks / how are you
  if (thanks.test(msgLower)) {
    return "You're welcome! 😊 I'm here whenever you want to learn more about cybersecurity. Got another question? I cover everything from strong passwords to network security and AI safety.";
  }

  // Question detection
  const isQuestion = questionWords.some(w => msgLower.startsWith(w) || msgLower.includes(` ${w} `));
  if (isQuestion) {
    return `That's a great question! 🤔 I cover many cybersecurity topics including:\n\n**Web Security** — XSS, SQL injection, buffer overflows\n**Network Security** — Firewalls, VPNs, MAC flooding, ARP spoofing\n**Malware & Threats** — Ransomware, viruses, trojans, DoS attacks\n**Authentication** — Strong passwords, MFA, access control\n**Social Engineering** — Phishing, pretexting, tailgating\n**Advanced Topics** — Zero-days, penetration testing, incident response, SIEM, threat hunting\n**AI Security** — Prompt injection, jailbreaking\n\nCould you ask about one of these specific topics? For example: "What is phishing?" or "How do firewalls work?"`;
  }

  // Default
  return "I'm your CyberAI Tutor! 🛡️ I can teach you about cybersecurity in a simple, friendly way.\n\nTry asking me about:\n- **Passwords** — How to create and manage them\n- **Phishing** — How to spot fake emails\n- **Firewalls** — How they protect networks\n- **Encryption** — How secret codes keep data safe\n- **Ransomware** — How to protect yourself\n- **AI Safety** — Prompt injection and jailbreaking\n\nWhat interests you?";
}
